# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing
# automatically fetch contract sources from Etherscan
autofetch_sources: true
networks:
  default: mainnet-fork
  mainnet-fork:
    cmd_settings:
#      fork: http://127.0.0.1:8545@11964336


